import React from 'react'
import {useValue} from 'react-cosmos/fixture'
import Parent from '../../stories/618'
import ChildOne from '../../stories/618/childOne'

const censusData = {
    'subFunctionCount': 7,
    'hc': 114,
    'cost': 2540644.9995105276,
    'costOfParentCostPercentage': 1,
    'reviewedPercentage': 0.058823529411764705,
    'pwcFunctions': [
        {
            'name': 'Executive & Other',
            'key': 'cf1',
            'id': 69,
            'subFunctionCount': 2,
            'hc': 2,
            'cost': 157890.49006158387,
            'costOfParentCostPercentage': 0.06214582914653661,
            'reviewedPercentage': 0,
            'pwcSubFunctions': [
                {
                    'name': 'Admin',
                    'key': 'csf1',
                    'id': 454,
                    'hc': 1,
                    'cost': 9089.95809423674,
                    'costOfParentCostPercentage': 0.057571283049987855,
                    'reviewedPercentage': 0,
                },
                {
                    'name': 'Executive',
                    'key': 'csf2',
                    'id': 457,
                    'hc': 1,
                    'cost': 148800.53196734714,
                    'costOfParentCostPercentage': 0.9424287169500122,
                    'reviewedPercentage': 0,
                },
            ],
        },
        {
            'name': 'Finance',
            'key': 'cf2',
            'id': 70,
            'subFunctionCount': 6,
            'hc': 12,
            'cost': 193134.64078191304,
            'costOfParentCostPercentage': 0.0760179563926175,
            'reviewedPercentage': 0,
            'pwcSubFunctions': [
                {
                    'name': 'Accounts Payable',
                    'key': 'csf3',
                    'id': 481,
                    'hc': 1,
                    'cost': 10226.567416264277,
                    'costOfParentCostPercentage': 0.052950456608206714,
                    'reviewedPercentage': 0,
                },
                {
                    'name': 'Accounts Receivable',
                    'key': 'csf4',
                    'id': 482,
                    'hc': 2,
                    'cost': 21142.66892930479,
                    'costOfParentCostPercentage': 0.10947113808122602,
                    'reviewedPercentage': 0,
                },
                {
                    'name': 'Controller',
                    'key': 'csf5',
                    'id': 484,
                    'hc': 1,
                    'cost': 51370.88769469076,
                    'costOfParentCostPercentage': 0.2659848460468497,
                    'reviewedPercentage': 0,
                },
                {
                    'name': 'General Accounting',
                    'key': 'csf6',
                    'id': 489,
                    'hc': 4,
                    'cost': 52613.56100000001,
                    'costOfParentCostPercentage': 0.27241907918223257,
                    'reviewedPercentage': 0,
                },
                {
                    'name': 'Tax Planning',
                    'key': 'csf7',
                    'id': 493,
                    'hc': 2,
                    'cost': 35166.56407899603,
                    'costOfParentCostPercentage': 0.18208315161186434,
                    'reviewedPercentage': 0,
                },
                {
                    'name': 'Treasury',
                    'key': 'csf8',
                    'id': 494,
                    'hc': 2,
                    'cost': 22614.39166265718,
                    'costOfParentCostPercentage': 0.1170913284696207,
                    'reviewedPercentage': 0,
                },
            ],
        },
        {
            'name': 'HR',
            'key': 'cf3',
            'id': 71,
            'subFunctionCount': 1,
            'hc': 3,
            'cost': 44991.09587399478,
            'costOfParentCostPercentage': 0.017708533023174277,
            'reviewedPercentage': 0,
            'pwcSubFunctions': [
                {
                    'name': 'HR Operations',
                    'key': 'csf9',
                    'id': 505,
                    'hc': 3,
                    'cost': 44991.09587399478,
                    'costOfParentCostPercentage': 1,
                    'reviewedPercentage': 0,
                },
            ],
        },
        {
            'name': 'Sales',
            'key': 'cf4',
            'id': 74,
            'subFunctionCount': 1,
            'hc': 4,
            'cost': 104266.63780466048,
            'costOfParentCostPercentage': 0.04103943597974063,
            'reviewedPercentage': 1,
            'pwcSubFunctions': [
                {
                    'name': 'Customer Service',
                    'key': 'csf10',
                    'id': 563,
                    'hc': 4,
                    'cost': 104266.63780466048,
                    'costOfParentCostPercentage': 1,
                    'reviewedPercentage': 1,
                },
            ],
        },
        {
            'name': 'Facilities & Real Estate',
            'key': 'cf5',
            'id': 75,
            'subFunctionCount': 1,
            'hc': 1,
            'cost': 16765.364,
            'costOfParentCostPercentage': 0.006598861314048188,
            'reviewedPercentage': 0,
            'pwcSubFunctions': [
                {
                    'name': 'Facilities & Real Estate',
                    'key': 'csf11',
                    'id': 469,
                    'hc': 1,
                    'cost': 16765.364,
                    'costOfParentCostPercentage': 1,
                    'reviewedPercentage': 0,
                },
            ],
        },
        {
            'name': 'Operations',
            'key': 'cf6',
            'id': 80,
            'subFunctionCount': 5,
            'hc': 75,
            'cost': 1757863.5639398147,
            'costOfParentCostPercentage': 0.6918965712559129,
            'reviewedPercentage': 0,
            'pwcSubFunctions': [
                {
                    'name': 'EHS',
                    'key': 'csf12',
                    'id': 549,
                    'hc': 1,
                    'cost': 30103.944005503523,
                    'costOfParentCostPercentage': 0.017125301771448637,
                    'reviewedPercentage': 0,
                },
                {
                    'name': 'Operations',
                    'key': 'csf13',
                    'id': 550,
                    'hc': 64,
                    'cost': 1552129.828822038,
                    'costOfParentCostPercentage': 0.8829637638903695,
                    'reviewedPercentage': 0,
                },
                {
                    'name': 'Procurement',
                    'key': 'csf14',
                    'id': 551,
                    'hc': 1,
                    'cost': 13791.800293640194,
                    'costOfParentCostPercentage': 0.007845774027382022,
                    'reviewedPercentage': 0,
                },
                {
                    'name': 'R&D',
                    'key': 'csf15',
                    'id': 553,
                    'hc': 2,
                    'cost': 37703.187,
                    'costOfParentCostPercentage': 0.021448301093116504,
                    'reviewedPercentage': 0,
                },
                {
                    'name': 'Supply Chain',
                    'key': 'csf16',
                    'id': 554,
                    'hc': 7,
                    'cost': 124134.80381863314,
                    'costOfParentCostPercentage': 0.07061685921768343,
                    'reviewedPercentage': 0,
                },
            ],
        },
        {
            'name': 'Undefined',
            'key': 'cf7',
            'id': 82,
            'subFunctionCount': 1,
            'hc': 17,
            'cost': 265733.2070485609,
            'costOfParentCostPercentage': 0.10459281288796984,
            'reviewedPercentage': 0,
            'pwcSubFunctions': [
                {
                    'name': 'Ambiguous/General',
                    'key': 'csf17',
                    'id': 575,
                    'hc': 17,
                    'cost': 265733.2070485609,
                    'costOfParentCostPercentage': 1,
                    'reviewedPercentage': 0,
                },
            ],
        },
    ],
}
const tbData = {
    'SG&A': {
        'entries': 149,
        'costCategoryCount': 4,
        'cost': 460988.75999999983,
        'costOfParentCostPercentage': 1,
        'reviewedPercentage': 0,
        'pwcFunctions': [
            {
                'name': 'Finance',
                'key': 'tsf1',
                'id': 70,
                'costCategoryCount': 1,
                'entries': 26,
                'cost': 192161.68000000002,
                'costOfParentCostPercentage': 0.4168467795180084,
                'reviewedPercentage': 0,
                'pwcCostCategories': [
                    {
                        'name': 'Insurance',
                        'key': 'tssf1',
                        'id': 498,
                        'entries': 26,
                        'cost': 192161.68000000002,
                        'costOfParentCostPercentage': 1,
                        'reviewedPercentage': 0,
                    },
                ],
            },
            {
                'name': 'Facilities & Real Estate',
                'key': 'tsf2',
                'id': 75,
                'costCategoryCount': 2,
                'entries': 54,
                'cost': 39716.06,
                'costOfParentCostPercentage': 0.08615407455921488,
                'reviewedPercentage': 0,
                'pwcCostCategories': [
                    {
                        'name': 'Office Expense',
                        'key': 'tssf2',
                        'id': 477,
                        'entries': 9,
                        'cost': 21847.78,
                        'costOfParentCostPercentage': 0.5500993804521395,
                        'reviewedPercentage': 0,
                    },
                    {
                        'name': 'Utilities',
                        'key': 'tssf3',
                        'id': 480,
                        'entries': 45,
                        'cost': 17868.280000000002,
                        'costOfParentCostPercentage': 0.4499006195478606,
                        'reviewedPercentage': 0,
                    },
                ],
            },
            {
                'name': 'Operations',
                'key': 'tsf3',
                'id': 80,
                'costCategoryCount': 1,
                'entries': 9,
                'cost': 2221.19,
                'costOfParentCostPercentage': 0.0048183170453006295,
                'reviewedPercentage': 0,
                'pwcCostCategories': [
                    {
                        'name': 'Warehousing & Distribution',
                        'key': 'tssf4',
                        'id': 560,
                        'entries': 9,
                        'cost': 2221.19,
                        'costOfParentCostPercentage': 1,
                        'reviewedPercentage': 0,
                    },
                ],
            },
            {
                'name': 'Undefined',
                'key': 'tsf4',
                'id': 82,
                'costCategoryCount': 1,
                'entries': 60,
                'cost': 226889.8299999998,
                'costOfParentCostPercentage': 0.4921808288774761,
                'reviewedPercentage': 0,
                'pwcCostCategories': [
                    {
                        'name': 'Undefined',
                        'key': 'tssf5',
                        'id': 585,
                        'entries': 60,
                        'cost': 226889.8299999998,
                        'costOfParentCostPercentage': 1,
                        'reviewedPercentage': 0,
                    },
                ],
            },
        ],
    },
    'nonSG&A': {
        'entries': 4,
        'costCategoryCount': 1,
        'cost': 2460000,
        'costOfParentCostPercentage': 1,
        'reviewedPercentage': 0,
        'pwcFunctions': [
            {
                'name': 'Non-SG&A',
                'key': 'tnf1',
                'id': 84,
                'costCategoryCount': 1,
                'entries': 4,
                'cost': 2460000,
                'costOfParentCostPercentage': 1,
                'reviewedPercentage': 0,
                'pwcCostCategories': [
                    {
                        'name': 'Other',
                        'key': 'tnsf1',
                        'id': 583,
                        'entries': 4,
                        'cost': 2460000,
                        'costOfParentCostPercentage': 1,
                        'reviewedPercentage': 0,
                    },
                ],
            },
        ],
    },
}
export default <Parent
    censusData={censusData}
    tbData={tbData}
>
    <ChildOne
        data="child"
    />
</Parent>
